networks:
  server:
    driver: bridge

include:
  - path: 
    - ./compose/gluetun.yaml
    - ./compose/jellyfin.yaml
    - ./compose/plex.yaml
    - ./compose/watchtower.yaml
    env_file:
      - ./environment/.env