networks:
  server:
    driver: bridge

include:
  - project_directory: .
  - path:
    - ./compose/utilites/deunhealth.yaml
    - ./compose/utilites/gluetun.yaml
    - ./compose/streaming/jellyfin.yaml
    - ./compose/download/nzbget.yaml
    - ./compose/streaming/plex.yaml
    - ./compose/download/qbittorrent.yaml
    - ./compose/utilites/watchtower.yaml
    env_file:
      - ./environment/.env